### PR TITLE
add save functionality for favourite articles

### LINKED ISSUE #15: Step 6
## Value Proposition
As a user I want to save the articles that i find interesting so that I can come back to them later
## Description
description_step6
### User should be able to :
- [ ] save their favourite articles after reading the full content
## Tasks
- [ ] add a "..." bookmark on the article on the full content page
- [ ] by clicking on this bookmark, the article is added to the collection page
- [ ] by clicking on an article title in the collection page, the full content of the article is display again in the content page, but this time the "..." bookmark is not to be seen
- [ ] add a "back" button on the collection page to return to the home page

### PR DESCRIPTION
**Pull request by anhthu253**
pls review!

### CODE REVIEW

**Review by Kheirah — CHANGES_REQUESTED** [review]
Good work so far!

Your "save to favorites" functionality is working fine. However, if I click on an article that I previously favorited, it doesn't display the correct article. It always displays the last visited article. That's something that needs fixing.

You further seem to have errors resulting from API calls.
2022-10-25 16_54_46-https___capstone-project-git-feature-savearticles-anhthu253 vercel app_content

Try looking into these two issues and request a review again when you're done 😄

**Comment by anhthu253** [comment]
Hi Kheirah, thank you so much for the review. I should have tested my implementation more thoroughly :)
I just fixed the bugs. Please let me know if it s ok now.

**Comment by Kheirah** [comment]
Very good work @anhthu253 ! Favorited articles are working now 🥳 

If you don't mind me bothering you a little more, there's a 403 error concerning images. I don't know the cause, but it's worth looking into it. I was testing it with the election keyword, by the way. It could very well be an issue with the API and not your app. I'll approve your changes so far.
2022-10-26 08_55_20-https___capstone-project-64vw0h3pf-anhthu253 vercel app

**Review by Kheirah — APPROVED** [review]
Looking good! Keep it up!

**Comment by anhthu253** [comment]
Good morning! And thank you very much!
Yeah I saw that error too but it s not always there. I do think it s the issue of the API. This API I m using actually has quite some problems. I will eventually have to look for a better API :(

**Pull request merged**
